config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  root to: "posts#index"
  get "/contact" => "pages#contact"
  get "/home" => "pages#home"
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    has_attachment :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # Index action to render all posts
  def index
    @posts = Post.all.reverse
  end

  # New action for creating post
  def new
    @post = Post.new
  end

  # Create action saves the post into database
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
  def edit
  end

  # Update action updates the post with the new information
  def update
    if @post.update_attributes(post_params)
      
      redirect_to post_path(@posts)
    else
     
      render :edit
    end
  end

  # The show action renders the individual post after retrieving the the id
  def show
        @post = Post.find(params[:id])
  end

  # The destroy action removes the post permanently from the database
  def destroy
    if @post.destroy
      
      redirect_to posts_path
    else
     
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :photo, :category, :author)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Blog Fertec</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= favicon_link_tag 'logo.png' %>
   <style> a, a:hover
{

    text-decoration: none;
    color:black;

}</style>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card">
            <div class="photo"></div>
            <div class="banner"></div>
            <ul>
                <li><b>Cyril Ferté</b></li>
                <li>Process Engineer & IT</li>

            </ul>
            
            <div class="social-media-banner">
                <a href="https://fr.linkedin.com/in/cferte"><i class="fa fa-linkedin"></i></a>
                <a href="https://github.com/cyrilferte"><i class="fa fa-github"></i></a>
                <a href="mailto:cyril@fertec.fr"><i class="fa fa-at"></i>cyril@fertec.fr</a>
               
            </div>
        
          </div>
    </div>
    <div class="col-md-4">
      <div class="card">
            <div class="photo"></div>
            <div class="banner"></div>
            <ul>
                <li><b>Charlotte Faure</b></li>
                <li>Chemical engineer</li>

            </ul>
            
            <div class="social-media-banner">
               
               <a href="mailto:charlotte.faure@contactory.co" color="black"><i class="fa fa-at"></i>charlotte.faure@contactory.co</a>
               
            </div>
        
          </div>
    </div>
    <div class="col-md-4">
      <div class="card">
            <div class="photo"></div>
            <div class="banner"></div>
            <ul>
                <li><b>Arn Jovic</b></li>
                <li>Industrial Engineer</li>

            </ul>
            
            <div class="social-media-banner">
                <a href="mailto:arn.jovic@contactory.co" color="black"><i class="fa fa-at"></i>arn.jovic@contactory.co</a>
            </div>
        
          </div>
    </div>
  </div>
</div>   
        
          <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
          <link href="https://fonts.googleapis.com/css?family=Lato:400,700,300" rel="stylesheet" />
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" />

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/_form.html.erb
  <div class="wrapper">
    <div class=" container form-signin">
<%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>
  
 <div class="form-group">
    <%= f.input :photo, as: :attachinary %>
  </div>
  <div class="form-group">
    <%= f.input :author, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :category, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :body, :as => :text, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>
</div>
</div>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render "posts/form" %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">


    <% @posts.each do |post| %>
    <div class="col-md-4 article-post">
    <article ng-repeat="post in posts" class="post">
        <div class="post-image" style="background:url('<%= post.photo? ? cloudinary_url(post.photo.path) : image_path("http://www.planwallpaper.com/static/images/colorful-triangles-background_yB0qTG6.jpg") %>')">
               
            <div class="post-author"><%=post.author? ? post.author : "Author" %></div>
        </div>
        <div class="post-card">
            
            <div class="post-cat"><%=post.category? ? post.category :  "category"  %></div>
            
            <a href="<%= post_path(post) %>" class="post-title"><h2><%= post.title %></h2></a>
            <div class="post-date"> <h6><%= post.created_at.strftime('%b %d, %Y') %></h6></div>
            <div class="post-content"><%= raw(post.body).truncate(500) %></div>
            <%= link_to "READ MORE", post_path(post) %>
            
        </div> 
    </article></div>
     <% end %>
</div></div>

app/views/posts/new.html.erb
<h2>Create New Post</h2>

<%= render "posts/form" %>

app/views/posts/show.html.erb
<div class="container">
  <div class=" blog-content">
    <h2 class="text-center"><%= @post.title %></h2>
    <h5 class="text-center"><%= @post.created_at.strftime('%b %d, %Y') %></h5>
    <h5 class="text-center"><%= @post.author %></h5><br><br>
    <div><%= raw @post.body %></div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Blog</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
        <li class="active"><%= link_to "Home", root_path %></li>
        <li><%= link_to "ADD", new_post_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script>$(window).scroll(function() {
  if ($(document).scrollTop() > 50) {
    $('nav').addClass('shrink');
  } else {
    $('nav').removeClass('shrink');
  }
});</script>